neighbor 10.95.90.153 {
        local-address 192.168.159.223;
        local-as 100;
        peer-as 100;
        family {
               ipv4 unicast;
               ipv4 link-state link-state;
        }
}

